spring.application.name=WFSuperLigaBot
bot.token = 8663966751:AAHr0ssC2tB-yzMWhSXgmMPBv5jP-W6-c04

spring.datasource.url=jdbc:mysql://wfslb-db:3306/wfslb-db
spring.datasource.username=root
spring.datasource.password=root